import Head from 'next/head'
import PokeCard from 'components/PokeCard/PokeCard'
import usePokeApi from 'hooks/usePokeApi'
import s from 'styles/Home.module.scss'

const Home = () => {
	const {
		data,
		loading,
		error,
		handleSearch,
		searchText,
		canLoadMore,
		nextPage,
	} = usePokeApi()

	return (
		<div className={s.home}>
			<Head>
				<title>Pokemon Finder</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<h1>Pokemon Finder</h1>
				<p>Busca tu pokemon favorito.</p>
				<input
					className={s.home__input}
					type="search"
					onChange={handleSearch}
					value={searchText}
					placeholder="Ingrese el nombre a buscar"
				/>
			</header>
			<main>
				<h2>Resultados de la búsqueda</h2>
				{loading && <p>Cargando...</p>}
				{error && <p>Error al cargar los datos</p>}
				{searchText && !data.length ? (
					<p>No se encontraron resultado para: {searchText}</p>
				) : (
					<>
						<ul className={s.home__list}>
							{data.map(pokemon => (
								<PokeCard key={pokemon.name} pokemon={pokemon} />
							))}
						</ul>
						{canLoadMore && (
							<button className={s.home__button} onClick={nextPage}>
								Cargar más
							</button>
						)}
					</>
				)}
			</main>
			<footer className={s.home__footer}>
				<p>Hecho por Juan David García</p>
				<a
					href="https://github.com/JuandaGarcia/pokeapi"
					target="_blank"
					rel="noopener noreferrer"
					className={s.home__footer__link}
				>
					Link a mi repo
				</a>
			</footer>
		</div>
	)
}

export default Home
